export const OPTION_SET_MOBILE_LAYOUT = 'OPTION_SET_MOBILE_LAYOUT'
export const OPTION_SET_GLOBAL = 'OPTION_SET_GLOBAL'
export const OPTION_GET_GLOBAL = 'OPTION_GET_GLOBAL'

export const SEARCH_DIALOG_SHOW = 'SEARCH_DIALOG_SHOW'
export const SEARCH_DIALOG_HIDE = 'SEARCH_DIALOG_HIDE'

export const OPTION_SET_INFINITE = 'OPTION_SET_INFINITE'
export const OPTION_INFINITE_SCROLL = 'OPTION_INFINITE_SCROLL'
export const OPTION_GET_INFINITE_SCROLL = 'OPTION_GET_INFINITE_SCROLL'
export const OPTION_INFINTE_LOADING = 'OPTION_INFINTE_LOADING'
export const OPTION_SET_INFINTE_LOADING = 'OPTION_SET_INFINTE_LOADING'
// export const OPTION_GET_INTERACTIVE = 'OPTION_GET_INTERACTIVE'
